version: '3.8'

services:
  klmelasticsearch-2:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.1.0
    container_name: elasticsearch-klm
    environment:
      - discovery.type=single-node
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - http.cors.allow-headers=Accept, Content-Type
      - http.cors.allow-methods=OPTIONS, HEAD, GET, POST, PUT, DELETE
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
    ports:
      - 9200:9200
      - 9300:9300
    mem_limit: 2g
